# application-dev.yml
spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://postgres:5432/orderdb}
    username: ${DB_USERNAME:orderuser}
    password: ${DB_PASSWORD:orderpass}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    open-in-view: false

  flyway:
    enabled: true

  kafka:
    bootstrap-servers: kafka:29092
    consumer:
      group-id: order-processing-group
      auto-offset-reset: earliest

management:
  endpoints:
    web:
      exposure:
        include: health,info

  endpoint:
    health:
      show-details: always